services:
  - type: web
    name: tripforge-api
    runtime: docker
    repo: https://github.com/pitiwxt/TripForgeAI
    rootDir: backend
    dockerfilePath: ./Dockerfile
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: DEBUG
        value: false
    healthCheckPath: /api/v1/health

  - type: web
    name: tripforge-frontend
    runtime: node
    repo: https://github.com/pitiwxt/TripForgeAI
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://tripforge-api-8ycx.onrender.com
      - key: NODE_ENV
        value: production
